name: Publish Book

on:
  push:
    branches:
      - master
    paths:
      - "book/src/**"

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: book

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4
        with:
          server: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          state-name: ${{ secrets.DEPLOY_KEY_BOOK }}
          local-dir: "book/dist/"
          log-level: minimal
